package backendAdministradorCompetenciasFutbolisticas.Enums;

public enum LogAccion {
    USUARIO_LOGIN,
    USUARIO_ERROR_LOGIN,
    USUARIO_ERROR_LOGIN_USUARIO_INACTIVO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION,
    USUARIO_ELIMINACION,
    USUARIO_CAMBIO_CONTRASENIA,
    USUARIO_RECUPERACION_CONTRASENIA,
    USUARIO_ALTA,
    USUARIO_BAJA,

    CLUBES_CREACION,
    CLUBES_MODIFICACION,
    CLUBES_ELIMINACION,

    JUGADORES_CREACION,
    JUGADORES_MODIFICACION,
    JUGADORES_ALTA,
    JUGADORES_BAJA,

    PASES_CREACION,
    PASES_MODIFICACION,
    PASES_ELIMINACION,

    JUEZ_CREACION,
    JUEZ_MODIFICACION,
    JUEZ_ELIMINACION,

    ASOCIACION_DEP_CREACION,
    ASOCIACION_DEP_MODIFICACION,
    ASOCIACION_DEP_ELIMINACION,

    COMPETENCIA_CREACION,
    COMPETENCIA_MODIFICACION,
    COMPETENCIA_ELIMINACION,

    PARTIDO_CREACION,
    PARTIDO_MODIFICACION,
    PARTIDO_ELIMINACION,



}
