package backendAdministradorCompetenciasFutbolisticas.Enums;

public enum LogAccion {
    USUARIO_LOGIN,
    USUARIO_ERROR_LOGIN,
    USUARIO_ERROR_LOGIN_USUARIO_INACTIVO,
    USUARIO_CREACION,
    USUARIO_MODIFICACION,
    USUARIO_ELIMINACION,
    USUARIO_CAMBIO_CONTRASENIA,
    USUARIO_RECUPERACION_CONTRASENIA,
    USUARIO_ALTA,
    USUARIO_BAJA,

    CLUBES_CREACION,
    CLUBES_MODIFICACION,
    CLUBES_ELIMINACION,

    JUGADORES_CREACION,
    JUGADORES_MODIFICACION,
    JUGADORES_ALTA,
    JUGADORES_BAJA,

    PASES_CREACION,

    TORNEOS_CREACION,
    ARBITROS_CREACION,
    PARTIDOS_CREACION,


}
