package backendAdministradorCompetenciasFutbolisticas.Enums;

public enum NombreTipoGol {
    JUGADA_COLECTIVA,
    JUGADA_INDIVIDUAL,
    JUGADA_PREPARADA,
    CABEZA,
    ERROR_DEFENSIVO,
    REMATE_LARGA_DISTANCIA,
    REMATE_CORTA_DISTANCIA,
    PENAL,
    TIRO_LIBRE_DIRECTO,
    TIRO_LIBRE_INDIRECTO,
    SAQUE_DE_META,
    OLIMPICO,
    CHILENA,
    TIJERA,
    VOLEA,
    REBOTE,
    RABONA,
    GOL_EN_CONTRA
}
